version: '2.1'
orbs:
  license-checker: monito/license-checker@2.0.1
  node: circleci/node
jobs:
  check-production-licenses:
    executor: node/default
    steps:
      - checkout
      - node/install-packages
      - license-checker/validate:
          forbidden: "MIT;"
workflows:
  test:
    jobs:
      - check-production-licenses
